### ISSUE TITLE
Unable to host this on Azure web app

### ISSUE THREAD

**Issue by AlexFielder** [hound-search/hound#246] opened 2017-03-23 10:43 UTC
Hi all,

In theory, given that Azure now includes go support by default, I should be able to run:

go get github.com/etsy/hound/cmds/...

and have Azure pull down the necessary files but when I run that I get the following:

> D:\home\site\wwwroot
> 'go' is not recognized as an internal or external command,
> operable program or batch file.

If I cd to d:\program files\go\1.7\bin and run it again I get:

> D:\Program Files\Go\1.7\bin
> go: cannot find GOROOT directory: c:\go

Is this simply a limitation of Azure web apps?

Thanks,

Alex.

**Comment by danielcb** [comment] 2017-04-28 12:12
I've no idea about Azure, but assuming it's some kind of windows machine you're working on:
The first error is because you're missing the path to go in your PATH variable and the second error is because your goroot is set to C:\go which seems to be not available?

```
set GOROOT=D:\go
mkdir D:\go
go get ..
```

**Comment by AlexFielder** [comment] 2017-05-12 10:19
Hi @danielcb,

When I originally posted this, I was attempting to use an Azure web app instance to host hound. It looked like a winner because the web apps have go already installed.

I posted this error in a couple of places (Stackoverflow & Microsoft's forum) and got a couple of responses there but wasn't able to figure it out. I don't believe it's the fault of Hound itself, but thought I would post here in case anyone else had tried it and managed to get it working.

Thanks,

Alex.

**Comment by dschott68** [comment] 2020-06-28 19:59
Hi.  Where you able to get GO setup for Azure from the responses in the other forums?

**Comment by AlexFielder** [comment] 2020-06-29 14:52
No, I never managed it. :(

**Comment by vipulgupta2048** [comment] 2020-08-09 17:00
Hey @dschott68 so I have picked up on this and it has been days since the Houndd's indexer just keeps on running and never stops. My config file is about 3800 URL's so maybe that's taking some time. Here's what I am doing 

App Service --> Linux Docker Container --> Deploying my own Docker Image --> with the last command as houndd
I will report back if it runs or not. But, I feel it's a problem of Azure since my local machine was able to run houndd in under 12 minutes. Fully indexed and showing results happily.

**Comment by vipulgupta2048** [comment] 2020-08-09 17:03
I also tried using container instances which didn't work out, as its FQDN didn't bind to the right port.

**Comment by salemhilal** [comment] 2020-08-10 12:52
@vipulgupta2048 Regardless of what happens, we're investigating updating the official Hound docker image, which might make things a little easier. Are you able to load the Hound UI in your browser?

**Comment by vipulgupta2048** [comment] 2020-08-11 11:28
Hey @salemhilal Thanks for replying, I just checked my Azure instance and it still shows `Hound is not ready` which either means the container is getting started again and updating its index. Or it hasn't indexed everything yet (after 4 days of running, not probable) To answer your question, yes I was able to load Hound UI in my browser once, but on refreshing it again showed Hound is not ready.

I don't feel anything is wrong with Hound as I mentioned before, since I was able to deploy it on my RPi4 (4GB) instead quite easily. I used a Balenalib base image for ARMv7hf with alpine and golang installed. Indexed 300 GitHub URL's in 4 hours, and whenever I start it up again. It gets ready in 2 minutes or less.

**Comment by vipulgupta2048** [comment] 2020-08-11 11:33
Also, something more to mention, the `healthz` endpoint shows a :+1: so that's something positive.

**Comment by salemhilal** [comment] 2020-08-17 23:31
@vipulgupta2048 got it. I know very little about Azure hosting unfortunately. I'd check in with Azure support to see if they can offer any guidance on how to narrow this issue down. Since there isn't a reproducible bug, I'm going to close this issue for now. If you come across anything, feel free to reopen this issue and we can take a look.

**Closed by salemhilal** 2020-08-17 23:31 UTC
Labels: question
